input_shape: [28, 28, 1]

alpha: 0.4
beta: 0.001
n_inner_gradient_steps: 3
n_finetune_gradient_steps: 3

n_steps: 50000
val_interval: 100

root_log_dir: logs
meta_batch_size: 32 # Number of tasks to sample in a batch
meta_batch_size_eval: 64